name: NASA Project
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env: 
    # This is set to exit watch mode and for React to know that
    # this is a workflow 
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.8.0
        with: ${{matrix.mongodb-version}}
      - run: npm install
      - run: npm run build --prefix client